### ISSUE TITLE
Plugins conflicts & MySQL/MariaDB support

### ISSUE THREAD

**Issue by Pyario** [Djaytan/mc-jobs-reborn-patch-place-break#2] opened 2022-12-06 01:17 UTC
Hello, I get an error when breaking down blocks in connection with jobs:

`[02:09:58 WARN]: [JobsReborn-PatchPlaceBreak] Violation of a place-and-break patch detected! It's possible that's because of a conflict with another plugin. Please, report this full log message to the developer: player=Diserix, jobs=Holzfäller, actionType=Break, blockMaterial=AIR, detectedPotentialConflictingPlugins=[Jobs, JobsReborn-PatchPlaceBreak]`

Up until now everything was fine, but suddenly the plugin started spamming after a few hours with this error every time you mine something, it thinks you're mining AIR apparently.

Jobs-Version: 5.1.1.1
Patch-Place-Break Version:  1.3.1-Snapshot

Best Regards

**Comment by Pyario** [comment] 2022-12-06 14:48
Edit: After a server restart everything was fine again, but probably. it's still a bug.

**Comment by Pyario** [comment] 2022-12-06 23:30
If you use the Mcmmo ability "Treefaller" and you use this plugin then it lags and the tps drop but that's only for big tree chains 500+ wood in one piece. I think less too. Would be nice if you could fix that.

**Comment by Djaytan** [comment] 2022-12-07 19:43
Hello @Pyario,

Thanks for your interest and for reporting the issue.

First thing which surprises me: how do you have acquired the version 1.3.1-SNAPSHOT of the plugin? Have you directly build the project by your own? This isn't recommended until the release has not been officially delivered. So, first try with the latest release available here: https://github.com/Djaytan/mc-jobs-reborn-patch-place-break/releases/tag/v1.3.0

Now, I think the error come from a reload of the JobsReborn plugin by using PlugMan or similar. Is it the case? It could be the explanation about the observed issue since the order of plugin loading matter. PlugMan seems to be able to modify it and finally break the patch like this is actually the case. I hadn't think about it before. Anyway I will try to find a better solution but it's possible that the best answer will be to just integrate the patch into JobsReborn plugin directly. This is something I'm wondering since a bit of time but the plugin still need a bit more work before expecting this. Another solution could be to unregistrer and register back the event listeners when an issue like that occurs: at most you will find one warning message like this but the plugin will manage to fix the issue by itself. The ideal would be to find a solution which will prevent the issue to ever happen but I need to inspect a bit more this situation.

For the McMMO issue, it is preferable to open another issue since it is not related to the one reported initially for this topic. Anyway, I will need to inspect that but if the issue is real two solutions are possible:
* Adding the possibility to store data in MariaDB, PostgreSQL or other database than SQLite which will permit to increase significantly a huge amount of parrallele I/O handling (SQLite can perform only one write/update operationb at a time whereas there isn't such a limitation for specialised RDBMS, or at least locks are far less restrictives) ;
* Creating a "whitelist" of blocks to be analysed by the patch plugin. This will prevent the scans of non-relevant blocks like sand, cobble, logs, etc and finally solve the issue.

I think the best will be to implement these two enhancements.

Simple question: does your server use a SSD or a HDD disk for storing data? It heavily matter in this situation.

Finally, to help me, you can provide me a generated report from Aïkar Timings command. Steps about how to use it can be found [here](https://www.spigotmc.org/wiki/timings/). Otherwise, do simply this:
* Run `/timings on` ;
* Wait few minutes, try do to laggy actions like using your McMMO skills in big trees ;
* Then do `/timings paste` and share the obtained link (in the newly created issue) ;
* Since I don't remember if the recording still in going or not after the paste, try using `/timings off` to preserve CPU cycles.

Thanks a lot!

**Comment by Pyario** [comment] 2022-12-07 20:50
1.:

So I use the plugin that you sent as a link, ie 1.30, but I have no idea why it shows me 1.3.1.

2.:

I have the Plugin not reloaded or something else.

3.:
I have a server hoster with a game server I think they use SSD.

4,:
 Here the Timings-Paste: https://timings.aikar.co/dev/?id=91084ecc77c74181ae134cf1bfbb7c20
 
 I hope its help.

**Comment by Djaytan** [comment] 2022-12-08 19:11
Thanks @Pyario,

I will work on fixing this issue.

**Comment by Djaytan** [comment] 2022-12-11 13:07
Finally, the solution will be easier: a cache strategy is going to be implemented.

I start working on the implementation.

**Comment by Djaytan** [comment] 2022-12-14 23:16
Automatic-fix attempt of detected conflicts with other plugins: https://github.com/Djaytan/mc-jobs-reborn-patch-place-break/commit/6f982607462bfd53cc6bb3bc2342e2a25b8afc81

For the performance issue:
* After some reflexions, the cache strategy didn't solve the reported issue. We can forgot about it.
* The best conceivable solution is the possibility to blacklist items through a configuration file.
* Giving the possibility to use a MariaDB database will help as well to improve performances.

**Comment by Pyario** [comment] 2022-12-16 15:05
Ok! :)

**Comment by Djaytan** [comment] 2023-01-01 14:54
MySQL support is now working. Some efforts need to be put in order to finalize it. I will have to do performances tests as well in order to compare results between SQLite and MySQL to verify if the plus-value is really present.

**Comment by Djaytan** [comment] 2023-01-03 23:03
Hello @Pyario,

Are you always interested by the fix?
If yes, will you being available soon (in few days) to test a release candidate of the plugin?
If again yes, have you a MySQL server available to use?

**Comment by Pyario** [comment] 2023-01-04 11:21
I can't test it right now because my server is currently no longer online due to a few things. I don't know when I can test it. Unfortunately, my server provider does not have a good MySQL connection and I don't like using MySQL either. :)

**Comment by Djaytan** [comment] 2023-01-04 14:32
Alright no problem. I know not everyone like to deal with the complexity added by a DBMS server like MySQL or MariaDB. Although this is why SQLite as been implemented for this plugin by following the trend that several other ones follow in the Bukkit ecosystem for the easy setup in end user side. When there is no SQLite provider, plugins generally only store information in raw files directly (e.g. Essentials).

Given this fact, the MySQL implementation isn't going to solve definitively the issue and the blacklist/whitelist of blocks feature remains required. This will solve problem you observed with McMMO. 
Since the work with MySQL come with the introduction a configuration logic, the implementation of this additional feature will be quick.

I will make directly a release of the new version after validating all the changes myself deeply.

**Comment by Djaytan** [comment] 2023-01-07 12:54
MySQL & MariaDB support merged into master.

**Comment by Djaytan** [comment] 2023-01-08 11:58
A consider this issue as done since the conflict auto-resolver attempt as been implemented as well as the MySQL/MariaDB support.

For the whitelist part (which is in fact what you want the most for your server), a new issue as been created here: #27

Feel free to consult the description of the issue and give feedback if you want.

**Closed by Djaytan** 2023-01-08 11:58 UTC
Labels: bug, enhancement
